### ISSUE TITLE
When publishing, the dependency versions in generated POM ignore lock file.

### ISSUE THREAD

**Issue by scrain** [nebula-plugins/gradle-dependency-lock-plugin#101]
When publishing with either Gradle's `maven` or `maven-publish` plugins, the generated POM file ignores the lock file and instead includes dependency versions as originally declared within the build file.

Sample project can be found [here](https://github.com/scrain/deplock-pom-issue).

**dependency declared in build.gradle**
```
dependencies {
    compile "org.slf4j:slf4j-api:1.+"
}
```

**lock info in dependency.lock**
```
"org.slf4j:slf4j-api": {
    "locked": "1.7.20",
    "requested": "1.+"
}
```
**sample from resulting POM file**
```
<dependency>
    <groupId>org.slf4j</groupId>
    <artifactId>slf4j-api</artifactId>
    <version>1.+</version>
    <scope>compile</scope>
</dependency>
```

**How to reproduce**  
Publish the sample project's artifact into your maven local...
```
./gradlew install 
```
...then open resulting the POM file.

If you'd rather not publish something into your maven local then instead run...
```
./gradlew writePom 
```
...and open POM file written into build dir.

**Comment by DanielThomas** [comment]
Yup, Gradle's default behavior - they publish the requested dependency details instead of selected. This plugin fixes that:

- https://plugins.gradle.org/plugin/nebula.maven-resolved-dependencies

**Comment by scrain** [comment]
Ah yes... I was just discovering that along with the https://plugins.gradle.org/plugin/nebula.maven-publish plugin.  Thanks for the quick reply.
