### ISSUE TITLE
Using a task alias for update, save, commit

### ISSUE THREAD

**Issue by itissid** [nebula-plugins/gradle-dependency-lock-plugin#104]
Hi I am not sure why this is happening, but the following code does not change the lock as I expect:

```
task lockTaskAlias {}
lockTaskAlias.dependsOn updateLock, saveLock, commitLock
```
I have a set of dynamic dependencies I have specified in the `updateDependencies` list. 

Running `./gradlew lockTaskAlias` does not update the lock as expected but 
`./gradlew updateLock, saveLock, commitLock` does. And the issue is reproducible(i.e. not a repository latency issue or somesuch). 

Looking at the debug log it seems to suggest that the dependency in the plugin does not resolve to the newer version, but the older one in the case of running the alias. 

This maybe just an issue with my understanding of gradle. But not entirely sure.

**Comment by rspieldenner** [comment]
so we are manually checking for the presence of certain tasks on the command line to not apply the lock. We need to do this before the taskGraph is ready so it is a string match
