### ISSUE TITLE
Provide option to select latest version where there are conflicts

### ISSUE THREAD

**Issue by ggascoigne** [nebula-plugins/gradle-dependency-lock-plugin#106]
When gradle encounters transitive dependencies that result in conflicting versions it's simply selects the latest version.

Is there any way to make this plugin do the same?

For instance on some of our larger builds we're getting failures like this.

```
:generateGlobalLock FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':generateGlobalLock'.
> Could not resolve all dependencies for configuration 'detachedConfiguration1'.
   > A conflict was found between the following modules:
      - org.slf4j:slf4j-api:1.7.7
      - org.slf4j:slf4j-api:1.6.0
      - org.slf4j:slf4j-api:1.6.1
      - org.slf4j:slf4j-api:1.7.13
      - org.slf4j:slf4j-api:1.7.2
```

Is the only solution to go through every dependency and exclude this package and only specify the version we want once, explicitly?

**Comment by DanielThomas** [comment]
@ggascoigne the only reason you'd see that is if you had `failOnVersionConflict()` enabled. Are you saying those same configurations resolve successfully without dependency lock?

**Comment by ggascoigne** [comment]
They do, the build works fine.  

That said, we do have`failOnVersionConflict() set and I'm not at all sure why, so in the short time I might just take that out.

**Comment by DanielThomas** [comment]
It's going to resolve _every_ configuration, which you won't do for a regular build. Check that every configuration has the appropriate excludes/forces/etc to avoid the conflict if you want to continue using strict conflict resolution.
