### ISSUE TITLE
Multi module project with scala plugin fails when using global.lock

### ISSUE THREAD

**Issue by StFS** [nebula-plugins/gradle-dependency-lock-plugin#120]
If I generate a global lock, any subsequent builds of my project fail. If I delete the `global.lock` file, the build succeeds.

I haven't dug into exactly whether there is something specific in our code that is causing this or whether this happens with any project that has the scala plugin applied to it. I can try to create a minimal test project but I wanted to see if anybody has had this experience and might have some input into how to get around it.

Here is the failure that I'm seeing:

```
:model:compileScala FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':model:compileScala'.
> scala.collection.immutable.$colon$colon.hd$1()Ljava/lang/Object;

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

**Comment by StFS** [comment]
A little update on this. I've been trying to figure out what the problem is for the past hour and I'm not really any wiser. However, I did just try to use the non-global locking mechanism and that does look like it works. At least, the compile phase finishes successfully on all my projects so I'm not getting the same error as when I have a `global.lock` file present.
However, we do sort of like the global.lock pattern better than having lock files in each project so I wold still like to know whether anybody has a solution to this problem.

**Comment by DanielThomas** [comment]
@StFS certainly possible there's an interaction issue between global locks and configurations used by the Scala plugin - global locks affect all configurations, based on an all-configurations, all-project view of dependencies.

Global dependency locks were a stop-gap implementation to fix classpath and tooling API issues on earlier versions of IntelliJ and Gradle. Since 2016.3, IntelliJ supports per-source-set modules, and will reflect the same classpath as the underlying Gradle build.

There are also correctness and supportability issues with global locks:

- Global locks are an entirely fake view of dependency resolution, and unsuitable for any project that produces artifacts used in other projects. It is impossible to reflect the influence of global locks on transitive dependencies, when they're consumed downstream
- Tooling configurations (such as for Findbugs, etc) pollute the global lock, and affect other configurations

We'd recommend avoiding them if you can.

**Comment by StFS** [comment]
Thanks for your reply @DanielThomas!

We'll be fine using the per-project locks and everything seems to work fine with them.

Just one thing that struck me was what you said about the per-source-set modules in IntelliJ. Up until now, I've just been annoyed with that feature so I've actually been un-checking that option when I import my gradle projects into IntelliJ. I've never really gotten the point of it.

I'll be completely honest and admit that I'm still not quite getting the point of them, even with what you said above. Are you saying that I'll have to generate per-source-set modules if I want my IntelliJ project to work properly with this plugin? As I said, I've turned that off and just have one module per gradle project, and that seems to be fine for me... at least so far. Should I be on the lookout for any particular kind of problem after applying the dependency lock plugin to my projects?

**Comment by rspieldenner** [comment]
If you happen to have skew across your projects, like different versions of
guava or apache commons and your sub projects depend on one another odd
things may happen without source set per module

**Comment by tomnis** [comment]
I just ran into this recently. 

It looks like the global lock file is overriding the version of scala-library used by zinc:

```
zinc - The Zinc incremental compiler to be used for this Scala project.
\--- com.typesafe.zinc:zinc:0.3.15
     +--- org.scala-lang:scala-library:2.10.6 -> 2.11.8
     +--- com.typesafe.sbt:incremental-compiler:0.13.15
     |    +--- org.scala-lang:scala-compiler:2.10.6 -> 2.11.5
     |    |    +--- org.scala-lang:scala-library:2.11.5 -> 2.11.8
     |    |    +--- org.scala-lang:scala-reflect:2.11.5
     |    |    |    \--- org.scala-lang:scala-library:2.11.5 -> 2.11.8
     |    |    +--- org.scala-lang.modules:scala-xml_2.11:1.0.3
     |    |    |    \--- org.scala-lang:scala-library:2.11.4 -> 2.11.8
     |    |    \--- org.scala-lang.modules:scala-parser-combinators_2.11:1.0.3
     |    |         \--- org.scala-lang:scala-library:2.11.2 -> 2.11.8
     |    +--- org.scala-lang:scala-library:2.10.6 -> 2.11.8
     |    \--- com.typesafe.sbt:sbt-interface:0.13.15
     |         \--- org.scala-lang:scala-library:2.10.6 -> 2.11.8
     \--- com.typesafe.sbt:compiler-interface:0.13.15
          \--- org.scala-lang:scala-library:2.10.6 -> 2.11.8
```

Attempting to force the resolution doesn't change the behavior:
```
allprojects {
    configurations.zinc {
        resolutionStrategy.force "org.scala-lang:scala-library:2.10.6"
    }
}
```

We should be fine using per-project locks too, just wanted to provide a bit from my experience.

**Comment by rspieldenner** [comment]
yep we don't like global locks, and would like to delete them from the
plugin

They are too imprecise a hammer
