### ISSUE TITLE
generateGlobalLock fails with springboot gradle plugin

### ISSUE THREAD

**Issue by marvertin** [nebula-plugins/gradle-dependency-lock-plugin#121]
Minimal project with this issue is
https://github.com/marvertin/nebula-dependency-lock-not-work-withspringboot

command:
` gradlew clean build generateGlobalLock`

end with this result:

```
:innerprj:clean
:innerprj:compileJava
:innerprj:processResources NO-SOURCE
:innerprj:classes
:innerprj:findMainClass
:innerprj:jar
:innerprj:bootRepackage
:innerprj:assemble
:innerprj:compileTestJava NO-SOURCE
:innerprj:processTestResources NO-SOURCE
:innerprj:testClasses UP-TO-DATE
:innerprj:test NO-SOURCE
:innerprj:check UP-TO-DATE
:innerprj:build
:generateGlobalLock FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':generateGlobalLock'.
> Could not resolve all dependencies for configuration ':innerprj:detachedConfiguration37'.
   > Project :innerprj declares a dependency from configuration 'detachedConfiguration37' to configuration 'archives' which is not declared in the descriptor for project :innerprj.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 6.955 secs

```

**Comment by ItamarBenjamin** [comment]
👍

**Comment by HarelOpler** [comment]
any update regarding this?

**Comment by DanielThomas** [comment]
Certainly reproducible, but odd error - we usually see this kind of thing where there are dependency cycles, but that doesn't seem to be the case here:

https://github.com/gradle/gradle/issues/1638

Avoid global locks in preference for per-project locks. Uncertain if we'll fix this, as we're phasing out the use of global locks internally.

**Comment by rpalcolea** [comment]
As @DanielThomas , we won't fix this as we don't recommend global locks.

Gradle might introduce this concept in their core locking at some point but from nebula perspective, we will stick with current opinions and lean towards adopting Gradle's as it is inspired by our implementation
