### ISSUE TITLE
Locking on released versions and ignore dev

### ISSUE THREAD

**Issue by cajturner** [nebula-plugins/gradle-dependency-lock-plugin#125]
Hello! 
I am looking at using this plugin but I am having some unwanted behaviour.

I am locking my dependency to `6.+` but a development version is being locked rather than a released build such as `6.4.6`.  I have the same issue if the dev build is `6.4.6-rc1`.
Example:
```
"locked": "6.4.7-SNAPSHOT",
"requested": "6.+"
 ```
I think this is a common problem but I am unable to find any other posts.

Do you have any suggestions of how to prevent versions being locked to dev? 

Cheers!

**Comment by rpalcolea** [comment]
Hi, this is really gradle behavior.

`6.+` tells gradle anything about statuses.

You might want to explore component metadata rules to reject the versions that are snapshot or candidates automatically.
