### ISSUE TITLE
Replace org.codehaus.groovy.modules.http-builder:http-builder dependency

### ISSUE THREAD

**Issue by pjfanning** [nebula-plugins/gradle-dependency-lock-plugin#130]
This project no longer seems to be actively maintained and its json-lib dependency brings in some problematic dependencies. Commons-collections 3.2.1 and Commons-beanutils 1.8.0 have CVEs reported against them.

**Comment by rpalcolea** [comment]
This is now removed and will be released in https://github.com/nebula-plugins/gradle-dependency-lock-plugin/releases/tag/v8.0.0
