### ISSUE TITLE
lockfile very dirrerent depending on preceding build

### ISSUE THREAD

**Issue by zerogvt** [nebula-plugins/gradle-dependency-lock-plugin#135]
Hi,
the lockfiles produced are very different in the next 2 scenarios:
1. `gradle clean generateLock saveLock` 
2. `gradle clean build generateLock saveLock`
In both cases `includeTransitives` is set to true but in the second case (where locks is preceded by build) the lockfile is much longer/detailed.

Is that normal?
Thanks a mil

**Comment by DanielThomas** [comment]
I’d guess there must be configurations created by tasks on the fly included in the ‘build’ phase, that aren’t on the configuration container when you only run lock generation.

**Comment by zerogvt** [comment]
Closing this (covered by your answer).
Btw thanks for your answer and for sharing this code in the first place. Brilliant work :smile_cat:
