### ISSUE TITLE
QueryDSL locking not working

### ISSUE THREAD

**Issue by lukyer** [nebula-plugins/gradle-dependency-lock-plugin#136]
Hi,
we use this plugin for locking all our dependencies and it works very well except for QueryDSL library. I think it could be caused by multiple version levels used by QueryDSL.  See https://oss.sonatype.org/content/repositories/snapshots/com/querydsl/querydsl-jpa/4.1.5.BUILD-SNAPSHOT/maven-metadata.xml

Is it possible to workaround this somehow?

Thanks!

**Comment by rpalcolea** [comment]
You could probably skip dependencies via `skippedDependencies` 

https://github.com/nebula-plugins/gradle-dependency-lock-plugin/wiki/Usage

Feel free to re-open if this doesn't solve your issue
