### ISSUE TITLE
React Native project with the dependencies from node_modules doesn't need to be locked

### ISSUE THREAD

**Issue by heuism** [nebula-plugins/gradle-dependency-lock-plugin#137]
Hi guys,

thanks for the great plugin to lockdown dependencies. However, I ran into an issue with lock down dependencies in build.gradle as those dependencies from node_modules will be include as

```
compile project(':react-native-exit-app')
compile project(':react-native-background-timer')
compile project(':react-native-mixpanel')
compile project(':react-native-push-notification')
```

will have to put into

```
compile project(path: ':react-native-exit-app', configuration: 'default')
compile project(path: ':react-native-background-timer', configuration: 'default')
compile project(path: ':react-native-mixpanel', configuration: 'default')
compile (project(path: ':react-native-push-notification', configuration: 'default')){
    exclude group: "com.google.android.gms"
}
```

which then later on break the build for the react native mixpanel, but then when I remove the `path:` and `configuration: 'default'`. The build is normally function.

Is there a way to not lock down those `dependencies` above but only lock down these one:
```
compile 'com.google.firebase:firebase-core:12.0.1'
// If you are receiving Google Play API availability issues, add the following dependency
compile 'com.google.android.gms:play-services-base:12.0.1'
compile 'com.google.android.gms:play-services-gcm:12.0.1'
compile 'com.google.firebase:firebase-auth:12.0.1'
compile 'com.google.firebase:firebase-database:12.0.1'
```

One more thing, as I need to put `configuration: 'default'` for react-native-push-notification. That is why I need to put `com.google.android.gms:play-services-gcm:12.0.1` in.

Thank you

**Comment by rpalcolea** [comment]
Hi, sorry for the late response.

I think you would have two options.

1) ignore specific dependencies by using `skippedDependencies`
2) create a configuration for the ones that you don't want to lock and just lock the configurations that matter to you.

The 1st one might be the easiest to accomplish with this plugin (https://github.com/nebula-plugins/gradle-dependency-lock-plugin/wiki/Usage)

In the future, this plugin will have only a few opinions on top of Gradle core locking (https://docs.gradle.org/current/userguide/dependency_locking.html) which is inspired on this

In Gradle locking, as of Today, you can't exclude some dependencies and you would have to lock the whole configuration. So number 2 might be appealing looking at the future.
