### ISSUE TITLE
Is there a possibility to create a runnable jar?

### ISSUE THREAD

**Issue by asangal** [nebula-plugins/gradle-dependency-lock-plugin#140]
Is it possible for gradle-dependency-local-plugin to create a runnable JAR (i.e. in environments where remote access to compile time/runtime dependencies is not available, any dependency needs to be screened/approved first before uploading those dependency jars to a binary repo (Artifactory)). If we could create a Runnable jar then, that'll save a lot of time in finding all deep down dependencies for trying out this plugin in Gradle build process.

**Comment by rahulsom** [comment]
Hi @asangal That looks more like a job for https://github.com/johnrengelman/shadow
