### ISSUE TITLE
Broken POM of version 7.0.1

### ISSUE THREAD

**Issue by GFriedrich** [nebula-plugins/gradle-dependency-lock-plugin#149]
Currently the POM of version 7.0.1 is broken as it doesn't contain the necessary dependency to Jackson.
This dependency was added to the dependency lock of this plugin exactly one commit after the 7.0.1 was released.
Please either fix the POM or create a new release.
Thanks in advance.

**Comment by rpalcolea** [comment]
Hi @GFriedrich , thanks for the report

We just released Version 7.1.0 which uses Square Moshi instead of jackson.

Things should be good now.

Feel free to close the ticket

**Comment by GFriedrich** [comment]
@rpalcolea: Oh wow, that was fast. Works like a charm now. Thx!
