### ISSUE TITLE
Supply chain attack prevention

### ISSUE THREAD

**Issue by colltoaction** [nebula-plugins/gradle-dependency-lock-plugin#159]
This plugin is great for dependency version checks, but is just shy of being also helpful for preventing supply chain attacks. Once we have a locked dependency version, we would also like to verify that the distributed binaries match the ones we used when we locked the version.

There already exists a gradle plugin that tackles this, but it's outdated: https://github.com/signalapp/gradle-witness.

Adding this feature to `gradle-dependency-lock-plugin` would make a compelling case to introduce this plugin to the project I work on.

Thanks!

**Comment by rpalcolea** [comment]
Hi @colltoaction ,

Thanks for the report.

In the future, gradle-dependency-lock-plugin will leverage a few opinions on top of gradle dependency lock mechanism (core locking) -> https://docs.gradle.org/current/userguide/dependency_locking.html

It would be interesting to chat with gradle folks about this instead.

I'd suggest to open an issue in https://github.com/gradle/gradle
