### ISSUE TITLE
Still download all dependencies at gradle 5

### ISSUE THREAD

**Issue by davidasync** [nebula-plugins/gradle-dependency-lock-plugin#165]
Sorry for noob question,
I well aware that readme has said that this plugin is compatible with gradle version `3.4.1` and `4.4.1`

Does it mean, this plugin no longer works for gradle 5 ?

Here's my build.gradle at root project
```
buildscript {
  repositories {
    maven {
      url "https://maven-central-asia.storage-download.googleapis.com/repos/central/data"
    }

    maven {
      url "https://plugins.gradle.org/m2/"
    }

    mavenCentral()
    jcenter()
    mavenLocal()
  }
  dependencies 
    classpath "com.netflix.nebula:gradle-dependency-lock-plugin:7.5.0"
  }
}

apply plugin: "nebula.dependency-lock"

wrapper {
  gradleVersion = '5.4.1'
  distributionType = "bin"
}

subprojects {
  apply plugin: 'java-library'

  sourceCompatibility = 1.7
  targetCompatibility = 1.7
  
  repositories {
    maven {
      url "https://maven-central-asia.storage-download.googleapis.com/repos/central/data"
    }

    maven {
      url "https://plugins.gradle.org/m2/"
    }

    mavenCentral()
    jcenter()
    mavenLocal()
  }
}

```

**Comment by chali** [comment]
Hi @davidasync the plugin needs to be at least version `7.0.0` to work with Gradle 5. I think you might actually encounter problems when running any version `7.+` on lower Gradle than 5. We internally bundle plugins with one Gradle version so we don't invest to heavy backward compatibility testing and support. Hopefully, this answer helped to clarify your question.

**Comment by davidasync** [comment]
> Hi @davidasync the plugin needs to be at least version `7.0.0` to work with Gradle 5. I think you might actually encounter problems when running any version `7.+` on lower Gradle than 5. We internally bundle plugins with one Gradle version so we don't invest to heavy backward compatibility testing and support. Hopefully, this answer helped to clarify your question.

Thank you for replying my issue, but when I executed generateGlobalLock
I got this errors,

```
* What went wrong:
Execution failed for task ':generateGlobalLock'.
> Could not resolve all dependencies for configuration ':detachedConfiguration1'.
   > Could not resolve project :common-cache.
     Required by:
         project :
      > Project : declares a dependency from configuration 'detachedConfiguration1' to configuration 'archives' which is not declared in the descriptor for com.accom:common-cache:1.1.0.
```
