### ISSUE TITLE
Add checksum to lock file

### ISSUE THREAD

**Issue by jmnas** [nebula-plugins/gradle-dependency-lock-plugin#43]
I'm wondering if it is possible to (optionally) add the sha1 of each dependency to the lock file and verify it when the dependencies are resolved? This would be useful for the paranoid and for people that have dependencies that are known to be updated in place from time to time.

**Comment by rspieldenner** [comment]
I haven't seen the need for this at my employer so I won't be implementing it. However I'm more than happy to accept a contribution.

**Comment by jmnas** [comment]
Ok I'll look into it. If you have any thoughts on how to do this let me know.

**Comment by bmuschko** [comment]
@jmnas If you need this, you could easily build a plugin that use the functionality of gradle-dependency-lock-plugin and additionally writes checksum files. I am going to close this issue for now. So far nobody else needed this functionality and we don't necessarily want to support edge cases.
