### ISSUE TITLE
Handle forces on individual dependencies when creating global locks

### ISSUE THREAD

**Issue by rspieldenner** [nebula-plugins/gradle-dependency-lock-plugin#58]
We should be able to handle:

```
dependencies {
  compile('<group>:<name>:<version>') { force = true }
}
```

**Comment by datallah** [comment]
This may be slightly different, but I've noticed applying a force in the configurations resolutionStrategy worked in 3.1.0, but no longer works in 4.1.2:

```
    configurations {
        all {
            resolutionStrategy {
                // org.jboss.resteasy:resteasy-jaxrs:2.3.10.Final looks for 'org.jboss.spec.javax.ws.rs:jboss-jaxrs-api_1.1_spec:1.0.2.Final', which doesn't exist in maven
                force 'org.jboss.spec.javax.ws.rs:jboss-jaxrs-api_1.1_spec:1.0.1.Final'
            }
        }
    }
```

In my case, I have some direct dependencies which have versions of transitive dependencies that don't exist in public repositories, so this is a workaround that had been working.

**Comment by rpalcolea** [comment]
This should work with modern versions of the plugin and gradle
