### ISSUE TITLE
Plugin doesn't work with Gradle 1.8 or 1.9 (at least)

### ISSUE THREAD

**Issue by pmorch** [nebula-plugins/gradle-dependency-lock-plugin#60]
Please include information about supported gradle versions in [README.md](https://github.com/nebula-plugins/gradle-dependency-lock-plugin/blob/gradle-2.2/README.md). It doesn't work for < 2.0 and [doesn't work for >= 2.4 either](https://github.com/nebula-plugins/gradle-dependency-lock-plugin/issues/56)

For `gradle-1.8` and `gradle-1.9`:

    jtest3> ../gradle-1.9/bin/gradle -g $(pwd)/gradleHome build

    FAILURE: Build failed with an exception.

    * Where:
    Build file '/bla/bla/build.gradle' line: 19

    * What went wrong:
    A problem occurred evaluating root project 'jtest3'.
    > org/codehaus/groovy/runtime/typehandling/ShortTypeHandling

    * Try:
    Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

    BUILD FAILED

    Total time: 5.366 secs

Works for `gradle-2.0`:

    jtest3> ../gradle-2.0/bin/gradle -g $(pwd)/gradleHome build
    :compileJava UP-TO-DATE
    :processResources UP-TO-DATE
    :classes UP-TO-DATE
    :jar UP-TO-DATE
    :assemble UP-TO-DATE
    :compileTestJava UP-TO-DATE
    :processTestResources UP-TO-DATE
    :testClasses UP-TO-DATE
    :test UP-TO-DATE
    :check UP-TO-DATE
    :build UP-TO-DATE

    BUILD SUCCESSFUL

    Total time: 5.853 secs

**Comment by rspieldenner** [comment]
This is on my todo list. No plans to support earlier versions. We accept pull requests if anybody wants to backport.

**Comment by pmorch** [comment]
I think it is totally fine, if gradle-dependency-lock-plugin requires gradle >= 2.0. Just in that case, please document it clearly so that I don't have to experience the malfunction and then only after attempting to download a newer version during other debugging attempts discover that the gradle version is at fault.

**Comment by rspieldenner** [comment]
Documented what versions we test against. Would release if anybody wanted to back port changes to an older version. Will accept pull requests to docs if anybody tests this against older versions.
