### ISSUE TITLE
Incomplete lock file being generated.

### ISSUE THREAD

**Issue by ftclausen** [nebula-plugins/gradle-dependency-lock-plugin#65]
We have lots of dependency configurations and the change in [6b95a9e](https://github.com/nebula-plugins/gradle-dependency-lock-plugin/commit/6b95a9e2a37b3ebcf9825df55a08e9cb943b2a4b) makes `generateGlobalLock` and `saveGlobalLock` generate an incomplete global lock file since only *one* configuration is being inspected (as best I can determine). We really do need to loop over each dependency configuration since each one has a different set of dependencies.

**Comment by rspieldenner** [comment]
Have you configured the list of configurations you want locked?

If you have and there is still a bug it should be fixed in the next major version. We're going to move to locking per configuration.

**Comment by ftclausen** [comment]
Ah, I should RTFM better - I take it this is specified in the "configurationNames" option?

**Comment by nadavc** [comment]
Yes, that's right - `dependencyLock.configurationNames` sets the configuration names to be considered for global lock. If none are specified, all configurations are considered (as of version 4.0). Please reopen the issue if you find a problem with this mechanism.
