### ISSUE TITLE
Add task to allow a single dependency to be locked to a specific version

### ISSUE THREAD

**Issue by DanielThomas** [nebula-plugins/gradle-dependency-lock-plugin#75]
It's a common ask to lock back a single dependency, without having to recalculate the entire lock file.

**Comment by jkschneider** [comment]
May make some ergonomic improvements, but this is currently possible with:

`./gradlew -PdependencyLock.override=group:artifact:version generateLock`

**Comment by DanielThomas** [comment]
Hmm, but that would recalculate everything else right? In this case, they want to keep everything they have now, but pin back one to a specific version?

**Comment by rspieldenner** [comment]
Shall fix updateLock to actually work.

**Comment by rpalcolea** [comment]
Looks like this is done via

```
Update lock (the lock must still be saved/committed):

./gradlew updateLock -PdependencyLock.updateDependencies=com.example:foo,com.example:bar
``` 

closing now
