### ISSUE TITLE
Option dependencyLock.lockAfterEvaluating only takes effect on the command line.

### ISSUE THREAD

**Issue by ftclausen** [nebula-plugins/gradle-dependency-lock-plugin#80]
The `dependencyLock.lockAfterEvaluating` option only takes effect when running via the command line, e.g.

    gdl -PdependencyLock.lockAfterEvaluating=false generateGlobalLock saveGlobalLock

I am attempting to fix this and found one solution by wrapping the [option detection line](https://github.com/nebula-plugins/gradle-dependency-lock-plugin/blob/v4.1.2/src/main/groovy/nebula/plugin/dependencylock/DependencyLockPlugin.groovy#L120) in a `project.afterEvaluate` block. This is probably not the correct solution because none of the standard extension properties need this treatment.

What I don't understand is: How are the other extension properties (e.g. `globalLockFile`) detected in the apply() method without using `project.afterEvaluate`?

**Comment by rspieldenner** [comment]
you'll never be able to read a property on an extension you create during configuration during configuration (users won't have a chance to set the property anywhere). The other properties work because they affect tasks, so they have a chance to look up what a user would set it to.

**Comment by ftclausen** [comment]
Thanks for that clarification!
