### ISSUE TITLE
Lock buildscript dependencies

### ISSUE THREAD

**Issue by apapia** [nebula-plugins/gradle-dependency-lock-plugin#88]
I would like to be able to use dynamic buildscript dependencies with the dependency lock.  Is this as simple as adding the apply lock logic to the project.buildscript.configurations or there some other issue?

**Comment by rspieldenner** [comment]
Unknown. I haven't tried to lock the buildscript yet. I know the buildscript classpath configuration isn't on the container we lock by default.

**Comment by apapia** [comment]
It appears to work with the following configuration:
`
project.generateLock {
    configurations = project.configurations + project.buildscript.configurations
}
`
This adds the buildscript dependencies to the lock file.  I'm not sure if this will work if there are conflicting configuration names but that isn't an issue for me.

**Comment by apapia** [comment]
Actually it looks like this only writes the lock to the lock file.  The lock doesn't appear to take effect during the build however.  I'll look at the source code to see if I can find a way to fix this.

**Comment by rspieldenner** [comment]
Would need to special case the build script forces

**Comment by grv87** [comment]
I think that plugin versions should be locked too

**Comment by DanielThomas** [comment]
Buildscript dependencies are what provide the plugin classpath so it can be applied, so it's not possible for a plugin to lock buildscript configurations. The `plugins` block also doesn't support dynamic dependencies.

An init file _would_ be called soon enough to add buildscript resolution strategies, but that would mean writing this logic in an init file that can apply to all your builds.

Likely the most productive way forward is to pursue a core locking feature for Gradle, a feature for lint to update plugins, or both.

**Comment by grv87** [comment]
+1 for implementing this in Gradle core

**Comment by rpalcolea** [comment]
Closing this as it is available at Gradle core level
