### ISSUE TITLE
generateGlobalLock issue

### ISSUE THREAD

**Issue by qinfchen** [nebula-plugins/gradle-dependency-lock-plugin#94]
When I run `./gradlew generateLock saveLock`, all lock files get generated properly.  But if I run `./gradlew generateGlobalLock saveGlobalLock`, the global lock file contains the dependencies only for the root :

```
{
    "baseline": {
        "com.palantir:gradle-baseline-java-config": {
            "locked": "0.4.0",
            "requested": "0.4.0"
        }
    }
}
```

Here is my dependency block in build.gradle at the root

```
allprojects {
     ...
    apply plugin: 'nebula.dependency-lock'
    dependencyLock {
        lockFile = 'dependencies.json'
        globalLockFile = 'global.json'
        dependencyFilter = {
            String group, String name, String version -> version ==~ /(\d+\.\d+\.\d+(\.|\-\d+)?)/
        }

        updateDependencies = []
        skippedDependencies = []
        includeTransitives = false
        lockAfterEvaluating = true
    }
}
```

I noticed that if remove the dependencyFilter, then global lock file gets generated properly. Am I doing something wrong?

**Comment by rpalcolea** [comment]
Closing this as we are not planning to support Global locks going forward.
We don't recommend using them and use lock per subproject instead
