### ISSUE TITLE
filter attempting to detect dynamic version yielding odd lock file

### ISSUE THREAD

**Issue by scrain** [nebula-plugins/gradle-dependency-lock-plugin#99]
Maybe more of a question than an issue, but I'd like a filter based just on any dependencies with a dynamic version defined, i.e. "1.2.+"  Using a simple `version.contains('+')` seems to perform some filtering, but yields a lock file with no "locked" attribute, but instead includes `"project": true`

I amended `GenerateLockTaskSpec` to show the issue here: https://github.com/scrain/gradle-dependency-lock-plugin/commit/02b6d2afb9526a50d0798f8b108c9c6b3fc5e574#diff-c48754782c852d0ece715bebe90ac62bR574

The actual result returned for the failing case I added is:

``` javascript
{
    "testRuntime": {
        "test.example:baz": {
            "project": true,
            "requested": "1.+"
        },
        "test.example:foo": {
            "project": true,
            "requested": "2.+"
        }
    }
}
```

**Comment by DanielThomas** [comment]
Filtering is obviously a problem for the `isKeyInPeerList` method of determining if a dependency is a project dependency:

                // If this dependency does not exist in our list of peers, it is a standard dependency. Otherwise, it is
                // a project dependency.
                if (!isKeyInPeerList(key, peers)) {
                    deps[key].locked = resolved.moduleVersion
                } else {
                    // Project dependencies don't have a version so they must be treated differently. Record the project
                    // as an explicit dependency, but do not lock it to a version.
                    deps[key].project = true

We'd be better off using the incubating `ComponentIdentifier` API to detect project dependencies:

    resolved.id.componentIdentifier instanceof ProjectComponentIdentifier

I assume that your intent is to only lock dependencies that require it: we're considering adding that as a feature to supersede transitive locks, and bring down the size of lock files.

**Comment by scrain** [comment]
Yes, that's exactly what I was after... only lock those dependencies defined with dynamic versioning schemes.  I have a work around in that the only dependencies we dynamically define are our own, so I can just filter by group for now, but we'd like to start expanding this to a few key 3rd party dependencies.  Thanks for the info.

**Comment by rpalcolea** [comment]
I expect this not to be an issue anymore
